### ISSUE TITLE
run.sh should error out on a bad CLI argument

### ISSUE THREAD

**Issue by milancurcic** [cdslaborg/paramonte#11]
Using run.sh provided in libparamonte_fortran_linux_x64_gnu_release_dynamic_heap_openmpi binary release.

Try:

```
$ ./run.sh --bad-arg
```

or similar. The script should give a helpful message to the user, but instead, nothing is output.

On a positive side, the status code is non-zero, as expected:

```
$ ./run.sh --bad-arg
$ echo $?
1
```

This is in reference to https://github.com/openjournals/joss-reviews/issues/2741

**Comment by shahmoradi** [comment]
Thanks, Milan for catching this subtle, albeit minor bug. The script was indeed able to capture the wrong input argument, however, an extra `\` prevented the relevant error messages to be displayed despite the script exiting with an error code. Since this is a minor correction to only the example's temporary run scripts, I have modified the existing release with this correction. The new binaries on the release page should resolve this issue now.
